deconz:
    image: "marthoc/deconz:2.09.00"
    container_name: deconz
    network_mode: host
    restart: always
    volumes:
#   original mapping from marthoc/deconz
#	  - /opt/deconz:/root/.local/share/dresden-elektronik/deCONZ
    - "./volumes/deconz:/root/.local/share/dresden-elektronik/deCONZ"
    - "/etc/localtime:/etc/localtime"
    devices:
      - /dev/ttyACM0
    environment:
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
      - DECONZ_DEVICE=0
      - DECONZ_VNC_MODE=0
      - DECONZ_VNC_DISPLAY=0
      - DECONZ_VNC_PASSWORD=0
      - DECONZ_VNC_PORT=5900
      - DECONZ_UPNP=1
#    # The command node is very important. It overrides
#    # the "gosu openhab tini -s ./start.sh" command from Dockerfile and runs as root!
#    command: "tini -s ./start.sh server"      
